language: java
dist: trusty
addons:
  sonarqube:
    token:
      secure: 23dbc7c1943f56b29d01baf1ef106456166306c8
      
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
